Hotfix: fix issue
ERROR Invalid configuration file
	Caused by: TOML parse error at line 4, column 1
  |
4 | multilingual = false
  | ^^^^^^^^^^^^
unknown field `multilingual`, expected one of `title`, `authors`, `description`, `src`, `language`, `text-direction`

Error: Process completed with exit code 101.